version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: posdb
      MYSQL_USER: pos
      MYSQL_PASSWORD: pospass
      MYSQL_ROOT_PASSWORD: rootpass
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppass"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/posdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: pos
      SPRING_DATASOURCE_PASSWORD: pospass
      # Adapt CORS to your frontend URL/port
      ALLOWED_ORIGINS: http://localhost:8080
    depends_on:
      - db
    ports: ["8081:8080"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports: ["8080:80"]
    depends_on:
      - backend
